name: Deploy Framely Backend to Azure

on:
  push:
    branches:
      - azure-deployment
    paths:
      - 'backend/**' # CI/CD triggers only from backend changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore dependencies
      run: dotnet restore ./backend/Framely.API/Framely.API.csproj

    - name: Build
      run: dotnet build ./backend/Framely.API/Framely.API.csproj -c Release --no-restore

    - name: Publish .NET app
      run: dotnet publish ./backend/Framely.API/Framely.API.csproj -c Release -o ./backend/publish

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: framely-backend
        package: ./backend/publish
