# .github/workflows/azure-deploy.yml
name: Deploy Framely Backend to Azure

on:
  push:
    branches:
      - azure-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish .NET app
      run: |
        cd backend
        dotnet publish -c Release -r linux-x64 --self-contained true -o ./publish

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: framely-backend
        package: backend/publish