name: Deploy Framely-Customer to Azure Static Web App

on:
  push:
    branches:
      - azure-deployment # CI/CD triggers only from deployment branch
    paths:
      - 'frontend/framely-customer/**' # Trigger only on frontend changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to Azure Static Web App
      - name: Deploy Framely-Customer
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CUSTOMER }} # Deployment token stored securely
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Enables PR-based workflows
          action: "upload"
          app_location: "frontend/framely-customer" # Path to Next.js app
          output_location: ".next" # Build output folder